language: java
env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "G1rOQJD_j0ZVAtUAh7ZQug"

addons:
  coverity_scan:
    project:
      name: "Eernie/JMoribus"
      description: "Your project description here"
    notification_email: oldenkamperwin@gmail.com
    build_command_prepend:
    build_command:
    branch_pattern: coverity_scan
